import { Activite } from './activite';
export const ACTIVITES : Activite[] = [
    { id: 1, name: 'Yoga', definition:'Les cours collectifs de Zen sont accessibles à toutes et à tous et ils plairont particulièrement aux personnes voulant travailler en douceur. Une séance dure 45 minutes et se déroule dans une ambiance détendue. Aucun saut ou impact sur le sol ne sera demandé, afin de préserver le dos et les articulations. Les exercices se font au sol, sur un tapis, et alternent contractions et étirements musculaires. Vous améliorerez votre souplesse et assurerez un équilibre indispensable à votre bien-être intérieur. Ce travail qui améliore votre flexibilité et votre force nécessite une respiration contrôlée et de la concentration.', plus:'Diminuer douleurs lombaires et dorsales, Renforcement musculaire, Améliore la souplesse et l’équilibre, Travail sur la posture et le souffle, Réduction de votre niveau de stress, Contribue à une meilleure concentration'},

    { id: 2, name: 'Zumba', definition:'Les cours collectifs de Zumba sont des programmes de danse-fitness d’inspiration latine, sur des rythmes entraînants et internationaux bourrés d’énergie. Accessible à toutes et à tous, quelque soit votre niveau de danse. Tout le monde est là pour s’amuser et se lâcher, sans prise de tête ! Votre coach vous plonge dans une ambiance dont vous ne pourrez plus vous passer. En un rien de temps, vous pourrez améliorer votre forme et décupler votre énergie. C’est simple, efficace et totalement grisant ! C’est un des meilleurs moyens de brûler des calories tout en s’éclatant. Une séance dure 45 minutes et vous aide à brûler environ 600 calories. Vous perdez du poids en passant un moment agréable, dynamique et ludique !', plus:'Diminuer les risques de problème cardio-vasculaire, Brûler les calories sans même vous en rendre compte.Tonification et renforcement musculaire. Augmenter l’endurance et la densité osseuse. Diminuer la masse grasse dans le corps. Se vider l’esprit tout en s’amusant' },

    { id: 3, name: 'Circuit training', definition:'Les cours collectifs de Circuit Training sont des cours complets sur une série de postes cardio et musculation. Une séance dure 45 minutes, en musique, et vous fait brûler environ 500 calories. Le circuit est adaptable au niveau de chacun et de vos objectifs. Contrairement aux entraînements traditionnels qui nécessitent des temps de récupération, les cours de Circuit Training optimisent la durée des séances. Votre coach compose les séances avec des exercices variés, afin de travailler différents groupes musculaires. Vous êtes sollicités sur le plan cardio-vasculaire et vous musclez l’ensemble de votre corps tout en améliorant votre endurance. Ces exercices sont sous forme de postes, ce qui permet d’éviter la lassitude, notamment grâce à la durée d’exécution très courte de chacun d’entre eux. Optimisez votre temps pour un maximum d’efficacité !' , plus:'Tonifier la silhouette et permet de raffermir tout le corps, Travailler les capacités cardio-vasculaires, et donc le souffle, Gagner en rapidité et en endurance, Améliorer la coordination et la vitesse, Brûler les graisses, Gagner en confiance en soi' },

    { id: 4, name: 'Body attack', definition: 'Les cours collectifs de « Attack » sont des entraînements cardios par excellence, inspirés de sports collectifs et athlétiques, dont l’objectif est de développer l’endurance et la force. Sous forme d’interval training (entraînement fractionné), vous combinez des mouvements aérobiques et des exercices de renforcement et de stabilisation. Autour de mouvements sportifs inspirés par l’athlétisme, le basket ou le patinage, travaillez de façon intensive votre endurance et sur votre résistance musculaire. Au programme, des mouvements simples (pliométrie, aérobic et course à pieds), pour un travail complet sur le haut et le bas du corps. À la fin de chaque séance, des étirements permettront une bonne récupération des muscles. Vous brûlerez beaucoup de calories (entre 500 et 800 calories). Le cours est accessible à toutes et à tous.Attack est un véritable défouloir pour évacuer le stress accumulé.', plus:'Corps aminci, Gain en vitesse, en puissance et en détente, Meilleure proprioception, Muscler et tonifier le bas et le haut du corps, Renfort et stabilité du corps et des articulations, Améliore la capacité cardio-vasculaire et donc le souffle' },
    
    { id: 5, name: 'Boxe' , definition:'Les cours collectifs de boxe vous font découvrir un sport de combat à part entière. Découvrez les rudiments de ces boxes avec techniques de jambe, de bras, balayage et projection. Accessible à tous, du débutant au confirmé. Cette activité se pratique avec du matériel : des gants, un casque et un protège-dents. Avec l’aide de votre coach, vous apprendrez différentes techniques de frappe, de défense et des stratégies de combat : la garde, les esquives, le crochet, l’uppercut, le low kick, etc. Les cours collectifs de boxe débutent toujours par un échauffement : course d’endurance, course de vitesse, abdominaux, pompes … Vos capacités cardio-vasculaires (coeur) et d’endurance seront sollicitées. Puis les étirements permettent ne pas brusquer vos muscles et gagner en souplesse. Et enfin, place au travail sur la technique qui se déroule généralement en binôme. La séance finit toujours sur un étirement qui permet d’éviter les risques de courbatures le lendemain.', plus:'Apprendre le respect et l’humilité, Confiance et maîtrise de soi, Travail sur la réactivité et la concentration, Gain d’endurance, de vitesse et de puissance, Évacuation du stress, Se défouler'},

    { id: 6, name: 'Cross Training', definition :'Les cours collectifs de Cross Training sont des entraînements complets, regroupant des mouvements cardio et renfo. C’est un travail en petite équipe motivée ! Ils vous permettent d’augmenter rapidement votre condition physique générale. Cette méthode est notamment utilisée par les sportifs qui ont besoin de combler une faiblesse musculaire et qui aimeraient passer à des entraînements à des exercices intensifiés. Avec une intensité plus élevée que des exercices classiques, vous solliciterez toutes vos chaînes musculaires. Vous enchaînerez gainages, squats, pull up, mais à un plus haut niveau. Votre coach est là tout au long de la séance pour veiller à ce que chaque participant exécute les postures de la bonne manière, afin d’éviter tout accident. ', plus:'Augmentation de la masse musculaire, Gain de vitesse et d’agilité, Gain d’endurance cardio-vasculaire, respiratoire et musculaire, Perte de poids rapide, Ambiance collective stimulante, La meilleure activité pour améliorer vos capacités physiques.' }
]